require "resources/data_item_modifier_electric_pole"
require "resources/data_item_modifier_assembler"
require "resources/data_item_modifier_furnace"
require "resources/data_item_modifier_mining"
require "resources/data_item_modifier_inserter"
require "resources/data_custom_input_zoom"
